### ISSUE TITLE
Meta index and store

### ISSUE THREAD

**Issue by at15** [xephonhq/xephon-k#25]
This is a tracking issue

When trying to implement Web UI #19 , the query need to filter series using tags, which previous implementation did not deal with. 

As InfluxDB guys [mentioned](https://www.influxdata.com/path-1-billion-time-series-influxdb-high-cardinality-indexing-ready-testing/) a tsdb can be treated as two parts, the index and the data
(Prometheus guys also mentioned it https://fabxc.org/blog/2017-04-10-writing-a-tsdb/ )

- [x] inverted index
  - [x] google `inverted index merge`
- [x] merge inverted index for `AND` `OR`
- [ ] change series id to int64
- [ ] bench high cardinality 
- [ ] mmap?
- [ ] (future) locality sensitive hashing
  - https://users.soe.ucsc.edu/~niejiazhong/slides/kumar.pdf
  - https://github.com/embr/lsh py
  - https://github.com/kayzhu/LSHash py
- [ ] (future) skip pointer
- [ ] (future) GEO location, like mentioned by elastic search  https://www.elastic.co/blog/found-elasticsearch-from-the-bottom-up 
  - could be pretty useful for IoT devices
  - https://www.elastic.co/guide/en/elasticsearch/guide/current/geohashes.html
- [ ] (future) distributed, a simplified version of elastic search
- [ ] (future) GPU accelerated

**Comment by at15** [comment]
Close in favor of #60 

The issue was thinking too much ... like most (all) of my projects (想太多 ...
