### ISSUE TITLE
Use Series intreface for both IntSeries and DoubleSeries

### ISSUE THREAD

**Issue by at15** [xephonhq/xephon-k#38]
Currently, only IntSeries is supported, and on the way of change time precision #35 (which is going over all the code), I decided to add double support at same time. And during work on hash the series #36, the new `Series` interface is added, so the API service, storage may all use this interface to avoid duplicate code and/or code generation at a cost of some condition and type cast (which I don't know how much it would cost).

TODO

- [x] read service #9  a29d4cf75e636d3afba88324327a336d0bd3acd8
- [x] write service #8 0db794bd36e2b3e2a69aeaf55296c10b2cbc6668
- [x] in memory store #3 
- [ ] double series code is copy and pasted
- [ ] on disk store (which has nothing implemented for now, it's the end of the quarter....) #32 
- [ ] cassandra store #11 

Future

- update the Cassandra backend, just need to figure out a way to not let it crash the build for now
